# Netlify configuration for Sandboxels with Gesture Control
[build]
  # Build command (if you have a build process)
  command = "echo 'No build process required for static site'"
  
  # Directory to publish (current directory)
  publish = "."

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Camera permissions for gesture control
    Permissions-Policy = "camera=self, microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # Content Security Policy for MediaPipe
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://www.googletagmanager.com https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; media-src 'self' blob:; connect-src 'self' https://cdn.jsdelivr.net; worker-src 'self' blob:; frame-src 'self' https:; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirects for SPA behavior (if needed)
[[redirects]]
  from = "/gesture-demo"
  to = "/gesture-integration.html"
  status = 200

# Force HTTPS redirect
[[redirects]]
  from = "http://sandboxels-gesture.netlify.app/*"
  to = "https://sandboxels-gesture.netlify.app/:splat"
  status = 301
  force = true

# Environment variables (set in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Edge functions for advanced features (optional)
[[edge_functions]]
  function = "gesture-analytics"
  path = "/api/gesture-stats"
